### ISSUE TITLE
实验报告模板看不懂。。

### ISSUE THREAD

**Issue by loheagn** [Roycent/ns_lab_guide#1]
不太清楚几个二级标题，比如虚拟化实施、基础设施配置等是什么意思，也不太明白三级标题中，环境准备、安装组件和部署环境有啥区别。。
助教能解释一下吗？

**Comment by Roycent** [comment]
（模板是老师给的）
基础设施的话大概指workstation的安装配置（对于ESXi来说它是我们给它准备的“硬件”基础设施）；虚拟化实施大概指ESXi的安装过程（相当于把workstation的“硬件”进行虚拟化）。至于三级标题，可以根据自己的情况进行增加、删除或者修改。二级标题也同样可以改。

**Comment by loheagn** [comment]
谢谢助教
看来要提前看一下vSphere的文档了。。

**Comment by loheagn** [comment]
> （模板是老师给的）
> 基础设施的话大概指workstation的安装配置（对于ESXi来说它是我们给它准备的“硬件”基础设施）；虚拟化实施大概指ESXi的安装过程（相当于把workstation的“硬件”进行虚拟化）。至于三级标题，可以根据自己的情况进行增加、删除或者修改。二级标题也同样可以改。

谢谢助教
看来要提前看一下vSphere的文档了。。

**Comment by Roycent** [comment]
也不至于…这只是我的理解，内容规定没有那么死板的
