### ISSUE TITLE
实验步骤

### ISSUE THREAD

**Issue by mikyan** [Roycent/ns_lab_guide#2]
以后实验步骤可以再写清楚些么，我真的找了好久都不知道怎么把新建的用户变成某个角色，这好耽误时间

**Comment by Roycent** [comment]
如果把每一步操作都截图给你们，那做这个实验还有什么意义呢？照着已经写好的实验报告复制一遍操作、复制一遍实验报告？百度搜索“vmware esxi 创建用户”，在第一页就可以得到具体的操作步骤，很耽误时间吗？也没有禁止你们使用搜索引擎、查看使用文档。
